[main]
appname = "Desktop Steam Market"

[window]
indent=[300,300]
width=1280
height=720
minw=640
minh=360

[synchronisations]
currency="UAH"
request_interval=12
cycle_interval=120
error_interval=1200