[main]
appname="Float Flower"
icon="./assets/images/logo.jpg"
version=0.7

[window]
indent=[300,300]
width=1280
height=720
minw=640
minh=360

[configs]
settings="./configs/settings.json"

[resources]
currencies="./resources/currencies.json"
proxies="./resources/proxies.json"

[sources]
dir="./sources"

